import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default [
    {
        ignores: ['**/node_modules/**', '**/out/**', '**/dist/**', '**/coverage/**', '**/generated/**', '**/src/syntaxes/**', '**/scripts/**', '**/pack/**']
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        files: ['packages/**/*.ts', 'packages/**/*.tsx'],
        languageOptions: {
            parser: tseslint.parser,
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: 'module'
            }
        },
        rules: {
            // Disable core rule conflicting with autogenerated Monarch grammar
            'no-useless-escape': 'off',
            '@typescript-eslint/explicit-function-return-type': [
                'warn',
                {
                    allowExpressions: true,
                    allowTypedFunctionExpressions: true
                }
            ],
            '@typescript-eslint/no-explicit-any': 'error',
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_'
                }
            ],
            'no-console': [
                'error',
                {
                    allow: ['info', 'warn', 'error']
                }
            ],
            '@typescript-eslint/no-non-null-assertion': 'error',
            // Disabled: requires type-aware linting (parserOptions.project), which
            // significantly increases lint time. Enable if type-aware linting is configured.
            '@typescript-eslint/no-floating-promises': 'off'
        }
    },
    {
        files: ['packages/**/*.test.ts'],
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-non-null-assertion': 'warn'
        }
    },
    {
        files: ['packages/cli/**/*.ts'],
        rules: {
            'no-console': 'off'        }
    }
];